### ISSUE TITLE
CYK & Checkpointing: > 100% table fill status

### ISSUE THREAD

**Issue by sjanssen2** [jlab/gapc#212]
I wonder why lines like `Info: Archived "dangle_table" table into "/Daten/Git/jlab/gapc_backward/out_580755_dangle_table". Table is 101.52% filled.` occur for cyk with activated checkpointing. Tables should not be filled more than 100% of course! I suspect this is an issue of resolution.
1. whenever a DP cell is computed, the internal counter is increased in the generated code: https://github.com/jlab/gapc/blob/f6e4bba602986625192f87856b41971f7671c35f/src/tablegen.cc#L486
2. when a checkpoint is dumped, the counter value is also dumped directly: https://github.com/jlab/gapc/blob/f6e4bba602986625192f87856b41971f7671c35f/src/checkpoint.hh#L945-L946
3. when loading a checkpoint the internal value is set to the previously dumped one: https://github.com/jlab/gapc/blob/f6e4bba602986625192f87856b41971f7671c35f/src/checkpoint.hh#L1196-L1197
4. however, the checkpoint mechanism for CYK "only" notes the loop variable value of the one or two outer loops (`z` and `y`), but not the position of the loops (`t_0_j` and `t_0_i`) for the current tile, e.g. 
```
for (int z = outer_loop_2_idx_start; (z < max_tiles_n); z += tile_size) {
#pragma omp for ordered schedule(dynamic)
      for (int y = ((inner_loop_2_idx_loaded) ? (z) : (inner_loop_2_idx_start)); (y < max_tiles_n); y += tile_size) {
        ++inner_loop_2_idx_loaded;
        mutex.lock_shared();
        unsigned int x = ((y - z) + tile_size);
        for (unsigned int t_0_j = y; (t_0_j < (y + tile_size)); ++t_0_j) {
          for (int t_0_i = x; (t_0_i > (x - tile_size)); t_0_i += -1) {
            nt_tabulate_iloop((t_0_i - 1), t_0_j);
            nt_tabulate_weak((t_0_i - 1), t_0_j);
            nt_tabulate_strong((t_0_i - 1), t_0_j);
            nt_tabulate_dangle((t_0_i - 1), t_0_j);
            nt_tabulate_ml_comps((t_0_i - 1), t_0_j);
            nt_tabulate_ml_comps1((t_0_i - 1), t_0_j);
            nt_tabulate_struct((t_0_i - 1), t_0_j);
          }
        }
#pragma omp ordered
        {
          // force omp to wait for all threads to finish their current batch (of size tile_size)
          inner_loop_2_idx = (inner_loop_2_idx + tile_size);
          outer_loop_2_idx = z;
          mutex.unlock_shared();
        }

      }
      inner_loop_2_idx = z;
    }
```
This leads to situations where some DP cells are computed twice and I think this is the reason for >100% values. @fymue do you agree? I am fine with the computing cells again, but do you see an easy way to fix the status computation?

**Comment by sjanssen2** [comment]
Hi @fymue,
it is indeed a bit tricky, because it depends on the timing. Here is what I did:
used gapc branch is `outside_cyk`
1. compile a single track, outside, CYK, checkpointing instance: `./gapc testdata/grammar_outside/nodangle.gap --cyk --checkpoint --outside_grammar ALL`
2. compile: `make -f out.mf`
3. execute with checkpoint dumping say fife seconds with a large input: `./out uacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguac -p "0:0:0:5"`. You here need to kill the program while in the inside phase right before a checkpoint is dumped (such that the amount of computed but NOT stored DP cells is high).
4. load the checkpoint and continue to dump every second a new checkpoint to see the table fill status messages: `./out uacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguacuacgugacguugacguguaucgguac -p "0:0:0:1" -I out_609411_checkpointing_log.txt`

**Comment by fymue** [comment]
Alright, I played around with this issue a bit and am not really sure anymore what actually causes this bug.

I tried to reproduce the bug using your description, but didn't manage to do so. The only time I was able to get a table% > 100% (100.84%) was when a table was already filled 100% during archiving. Whenever we dump the table indices, we currently do some `+/-1` offsetting to ensure that we don't archive an incomplete iteration. This can cause a table% > 100% after loading a table that was dumped being already 100% filled. In that case, we e.g. subtract 1 from the loop indices before dumping them, which means 1 additional loop iteration is executed after loading the table, which causes a table% > 100% since the tabulated counter is then incremented a couple more times. 

This `+/-1` offsetting before dumping is unnecessary though and can be removed (see #213 for reference). This fixes the case described above. 

@sjanssen2  Did you observe this bug multiple times? And if so, how much bigger than 100% were table% values in those cases? Since the 101.52% from your initial comment is pretty close to 100%, I think it could've also been caused by simply (falsely) re-executing 1 iteration that was already completed before archiving.

**Comment by sjanssen2** [comment]
Hi @fymue, I tend to agree. With your new changes in #213, I did not observe this behavior any more. The percentage above 100% was always in a range that was reasonable to be computed between two dumps, thus likely this +/- 1 issue. I will close this issue :-) Thank!
